source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ManfreddsAirport' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ManfreddsAirport
  
  pod 'SnapKit', '~> 3.0'
    
  target 'ManfreddsAirportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ManfreddsAirportUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
